name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY_DEV }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID_DEV }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME_DEV }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL_DEV }} \
            --alias devorg

      - name: Validate Deployment (NO DEPLOY)
        run: |
          sf project deploy start \
            --target-org devorg \
            --check-only \
            --test-level RunLocalTests
