name: Salesforce CI/CD

on:
  push:
    branches:
      - main
      - release/qa
      - release/prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'DEV' || github.ref_name == 'release/qa' && 'QA' || 'PROD' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --alias targetOrg

      - name: Deploy Metadata
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            sf project deploy start --target-org targetOrg
          else
            sf project deploy start \
              --target-org targetOrg \
              --test-level RunLocalTests
          fi
